### ISSUE TITLE
facet search cut when no results

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-frontend#575]
<img width="1680" alt="Screenshot 2022-02-24 at 09 19 53" src="https://user-images.githubusercontent.com/10883585/155485772-cd72194f-f725-48db-9a25-cee39e29a558.png">

**Comment by madewild** [comment]
It's because of the semantic search keywords...
example: https://kohesio.development.ec.europa.eu/projects?keywords=rome&policyObjective=Connected-Europe&sort=Total-Budget-(descending)&amountEUSupport=1-000-000-000---10-000-000-000

Related: verticall scrollbar still there sometimes
![filter_scroll](https://user-images.githubusercontent.com/942488/155488566-74fd23b0-4fbb-4720-933d-361a99cee015.png)

https://kohesio.development.ec.europa.eu/projects?keywords=sqhdsqdk&policyObjective=Connected-Europe&sort=Total-Budget-(descending)

**Comment by raphdom** [comment]
fixed
