### ISSUE TITLE
Error 404 page on one project fiche

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-frontend#678]
https://kohesio.test.ec.europa.eu/en/projects?sort=Total-Budget-(descending)&country=Poland&program=2014TC16RFIR004---ESPON
Clicking on the second project in the list->project 404 page
![image](https://user-images.githubusercontent.com/80402472/175339827-573a51d0-9a5d-4520-b531-07fd20a9d1cc.png)

**Comment by madewild** [comment]
https://linkedopendata.eu/wiki/Item:Q4295701 exists and it's a valid Kohesio project. So it looks like a problem with the index...

**Comment by madewild** [comment]
https://kohesio.development.ec.europa.eu/en/projects/Q4295701

**Comment by madewild** [comment]
https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q4295701

**Comment by D063520** [comment]
Ok it is fixed. The problem was that the query was timing out. (I increased the timeout from 2 to 3 sec). This might be related to the fact that this project has so many countries. We might need in future to analyze the query more in detail and try to optimize it

**Comment by D063520** [comment]
Ok it is fixed. The problem was that the query was timing out. (I increased the timeout from 2 to 3 sec). This might be related to the fact that this project has so many countries. We might need in future to analyze the query more in detail and try to optimize it

https://kohesio.test.ec.europa.eu/en/projects/Q4295701

the project loading is slowish
