### ISSUE TITLE
Editing feature - list of edits

### ISSUE THREAD

**Issue by gachpas** [ec-doris/kohesio-frontend#829]
when going to my list of edits, I just find 1 entry while I have updated 3 times the same fiche on the same day. 
Is it meant to be like that?  If done on different dates, would all the edits appear?
I would expect to find all the edits

Also the fact that the filter takes only the submitted is not evident, I would prefer to have the full list and being able to filter to reduce the list. Also having the possibility to sort based on the status, which is not allowed at the moment.

**Comment by raphdom** [comment]
Hey @gachpas,

So we have the concept of edits and versions.
Edit concept is a complete flow, from draft, submitted, approved, published
When it was approved, the public version in the project details becomes the change version
But each change that you do in the project will have a new version, can be a draft or even a submitted
You can always see all the versions clicking in the history button for each row:
![image](https://github.com/ec-doris/kohesio-frontend/assets/5124917/4e214990-3a11-44ae-ad93-07a23f7fa947)

The filter rule when you open the edits list page is different for each role
ADMIN's will  see all the edit by default
REVIEWER's will see with SUBMITTED filter applied by default
EDITOR's will see with DRAFT filter applied by default

This make sense when we think that REVIEWER's will only take care of approve the submitted versions and EDITOR's will only change data, create draft's and submit versions.

In normal situation maybe we are not going to have REVIEWER's changing the data and approving, otherwise if it is this the use case we could skip the SUBMITTED step otherwise it will be pointless the REVIEWER submit and approve. (you can always think about this possibility)

We can always improve the way that we present the filters, maybe only the indication (1) in the button is not enough and evident as you said.

The sort indeed, we don't have this on this release, I am going to create a new issue to improve that.

Thanks for all these points.

**Comment by gachpas** [comment]
Hello @raphdom ,

Thanks for the clarification and for opening the ticket about the sort.

Cheers,
