### ISSUE TITLE
Professional Space - remarks from collective testing REGIO

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-frontend#837]
- when I try to logout, I am redirected to kohesio.test and I am still logged in
- if you which between the current and previous draft you loose your current draft
- As a reviewer if you want to reject the submission there is no button revert to draft
- For reviewer is not obvious which projects are in draft mode
- sorting button on edits view for the created column does not work
- change from American format to european format for dates
- possibility to filter on a specific date period
- when a user submit the draft, he/she should not have the possibility to change again and re-submit
- when a review is looking into a project, he/she should be made aware that a draft is ongoing
- notify reviewers if draft are pending for too long (90 days ??)
- idea: restricting drafting right to the original version of the project and English ?
- Create a user profile to display what is your rights and your reviewer
- create a filter to see all projects that editors are allowed to modify
- ask for 'what changes and why' in the comment box
- idea: moving the submit box below the description to make more evident that 'save' is 'save as draft' and 'submit' is the next step in the process

**Comment by raphdom** [comment]
- when I try to logout, I am redirected to kohesio.test and I am still logged in
   _All environments, DEV, TEST and ACC are protected by EULogin. If you logout it will login again because you cannot access without login._

- if you which between the current and previous draft you loose your current draft
  _I think this is not the case anymore, can you check please?_

- As a reviewer if you want to reject the submission there is no button revert to draft
   _As a reviewer you can always save as draft instead of approve, this will rollback the submission to draft again_

- For reviewer is not obvious which projects are in draft mode
   _You can go to edits and check the draft's using the filter on the right_

- sorting button on edits view for the created column does not work
   _I have create a new issue for that, it will be an improvement in the professional space_
