### ISSUE TITLE
Relevancy rating for interreg projects

### ISSUE THREAD

**Issue by Dgojsic** [ec-doris/kohesio-frontend#978]
Currently, for many (especially small countries) the first several observations when sorting by relevancy are almost all exclusively Interreg (e.g. Austria, Belgium, Cyprus, Ireland, Luxembourg, Portugal). These should not be as "relevant" because they have many mostly mobile operation locations in many cities across Europe, and are not as impactful in a single country as non-interreg projects.
Idea is to by default reduce the relevancy rating for interreg projects, to push them down a bit.

**Comment by madewild** [comment]
@DiaZork can you propose a way?

**Comment by DiaZork** [comment]
So I've tested some things to check the performances and it doesn't cost performance to check if a project is interreg. 
So we can easily adapt the formula for them. (The current formula is $log(budget)^2 * readability$)

I've tried some queries, with different formula on France to check the order of the top 100 (the following formula are only for the interreg. The other project keep the default formula)
- $log(budget)^2 * readability$ (current) : 34 in top 100 and top 1 interreg is rank 14
- $log(budget*0.5)^2 * readability$ : 12 in top 100 and top 1 interreg is rank 40
- $log(budget*0.75)^2 * readability$ : 22 in top 100 and top 1 interreg is rank 25
- $log(budget)^2 * readability * 0.9$  : 8 in top 100 and top 1 interreg is rank 57

I've tried other formula like $log(budget) * readability$ but they are not interresting because they make the interreg project completely disappear 

**Netherlands**
- $log(budget)^2 * readability$ (current) : 81 in top 100 and top 1 interreg is rank 4
- $log(budget*0.5)^2 * readability$ : 62 in top 100 and top 1 interreg is rank 6
- $log(budget)^2 * readability * 0.9$  : 61 in top 100 and top 1 interreg is rank 9
- $log(budget)^2 * readability * 0.85$  : 50 in top 100 and top 1 interreg is rank 13

**All projects**
- $log(budget)^2 * readability$ (current) : 0 in top 100 and top 1 interreg is rank 323
- $log(budget*0.5)^2 * readability$ : 0 in top 100 and top 1 interreg is rank 743
- $log(budget)^2 * readability * 0.9$  : 0 in top 100 and top 1 interreg is rank 894

So with all this we have 2 different possibility $log(budget * x)^2 * readability$ and $log(budget)^2 * readability * x$ and we can set the constant to adapt the thing

If you want to give it a try here are the query (it has to be done in our endpoint)
```sparql
SELECT DISTINCT ?s0 ?keepId WHERE { 
	?s0 <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> . 
	?s0 <https://linkedopendata.eu/prop/direct/P474> ?budget1 . 
	?s0 <https://linkedopendata.eu/prop/direct/P32> <https://linkedopendata.eu/entity/Q20> . 
	OPTIONAL { 
    	?s0 <https://linkedopendata.eu/prop/direct/P590521> ?readabilityBase . 
		OPTIONAL {?s0 <https://linkedopendata.eu/prop/direct/P562941> ?keepId .} 
		BIND(IF(BOUND(?keepId), ?readabilityBase * 0.9, ?readabilityBase) AS ?readability) 
  	}
} 
ORDER BY DESC(<http://the-qa-company.com/qendpoint/#log>(?budget1) * <http://the-qa-company.com/qendpoint/#log>(?budget1) * ?readability) 
LIMIT 1000 OFFSET 0
```

```sparql
SELECT DISTINCT ?s0 ?keepId WHERE { 
	?s0 <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> . 
	?s0 <https://linkedopendata.eu/prop/direct/P474> ?budget1Base . 
	?s0 <https://linkedopendata.eu/prop/direct/P32> <https://linkedopendata.eu/entity/Q20> . 
	OPTIONAL { ?s0 <https://linkedopendata.eu/prop/direct/P590521> ?readability . }
	OPTIONAL { ?s0 <https://linkedopendata.eu/prop/direct/P562941> ?keepId . } 
	BIND(IF(BOUND(?keepId), ?budget1Base * 0.5, ?budget1Base) AS ?budget1) 
} 
ORDER BY DESC(<http://the-qa-company.com/qendpoint/#log>(?budget1) * <http://the-qa-company.com/qendpoint/#log>(?budget1) * ?readability) 
LIMIT 1000 OFFSET 0
```
